### ISSUE TITLE
"Open Millennium" button missing on latest Steam Families Beta update

### ISSUE THREAD

**Issue by Cynosphere** [SteamClientHomebrew/Core#12]
Steam Version:  1721420033

It would also be nice to have an alternative way to open Millennium in these cases, e.g. adding a new route to the steam:// protocol if possible. (If such a way already exists, it needs to be documented.)

**Comment by ShadowMonster99** [comment]
Steam has changed some of the classnames in the new beta update, so Millennium doesn't know where to mount. It has since been fixed in the beta version of Millennium, which you can install [here](https://docs.steambrew.app/users/installing)!

As for custom URI schemes, I wouldn't be able to address that as Millennium doesn't have privilege to change Steams URI scheme,
